import{a as v,i as a,S}from"./assets/vendor-BjmtRwYh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const p of o.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&s(p)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const q="https://pixabay.com/api/",E="45141895-b62da3b06f4b18f1184207a2c";async function g(t,r=1,i=15){const s={key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:i};try{return(await v.get(q,{params:s})).data}catch(e){throw new Error(e.response.status)}}let d;function h(t,r,i=!1){if(i||(r.innerHTML=""),t.hits.length===0){a.error({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",timeout:3e3,position:"topRight"});return}const s=t.hits.map(e=>`
      <li class="gallery-item-wrapper">
        <a href="${e.largeImageURL}" class="gallery-item">
          <img src="${e.webformatURL}" alt="${e.tags}" class="img" />
          <div class="container-properties">
            <ul class="list-properties">
              <li class="properties"><p class="text"><strong>Likes</strong> ${e.likes}</p></li>
              <li class="properties"><p class="text"><strong>Views</strong> ${e.views}</p></li>
              <li class="properties"><p class="text"><strong>Comments</strong> ${e.comments}</p></li>
              <li class="properties"><p class="text"><strong>Downloads</strong> ${e.downloads}</p></li>
            </ul>
          </div>
        </a>
      </li>`).join("");r.insertAdjacentHTML("beforeend",s),d?d.refresh():d=new S(".gallery a",{})}const P=document.querySelector(".form"),f=document.querySelector(".search"),y=document.querySelector(".btn"),b=document.querySelector(".loader"),m=document.querySelector(".gallery"),c=document.querySelector(".load-more");let l="",n=1;const u=15;f.addEventListener("input",R);P.addEventListener("submit",x);c.addEventListener("click",I);function w(){b.style.display="block"}function L(){b.style.display="none"}function R(){y.disabled=f.value.trim()===""}async function x(t){if(t.preventDefault(),l=f.value.trim(),l===""){a.error({title:"Error",message:"Please enter a search query.",timeout:3e3,position:"topRight"});return}n=1,w(),c.style.display="none";try{const r=await g(l,n,u);h(r,m),r.hits.length>0&&r.totalHits>u&&(c.style.display="block")}catch{a.error({title:"Error",message:"An error occurred while fetching images. Please try again!",timeout:3e3,position:"topRight"})}finally{L()}}async function I(){n+=1,w();try{const t=await g(l,n,u);h(t,m,!0),(n-1)*u+t.hits.length>=t.totalHits&&(c.style.display="none",a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.error({title:"Error",message:"An error occurred while fetching images. Please try again!",position:"topRight"})}finally{L(),$()}}function $(){const{height:t}=m.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}y.disabled=!0;
//# sourceMappingURL=commonHelpers.js.map
